// Generated by CoffeeScript 1.6.2
(function() {
  $(document).ready(function() {
    return $('div.container ul.list li').on("click", function() {
      return $(this).toggleClass("green");
    });
  });

}).call(this);
